# Generated by Django 4.1.4 on 2022-12-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_created=True)),
                ('nombre', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
    ]
